<?php
namespace backend\widgets;
use backend\models\Menu;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\bootstrap\Widget;


class MenuWidget extends Widget {
    //widget实例化后执行的代码
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    //widget被调用时，需要执行的代码
    public function run(){
        NavBar::begin([
            'brandLabel' => 'My shop 后台管理模板',
            'brandUrl' => \Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);
        $menuItems = [
            ['label' => '首页', 'url' => ['user/index']],
        ];
        if (\Yii::$app->user->isGuest) {
            $menuItems[] = ['label' => '登录', 'url' => ['user/login']];
        } else {
            //查找出所有的一级分类
            $menus = Menu::findAll(['parent_id'=>0]);
//            var_dump($menus);
            foreach($menus as $menu){
                //找到父类
                $item = ['label'=>$menu->label,'items'=>[]];
                //找到所有的子类
                $children = Menu::findAll(['parent_id'=>$menu->id]);
               foreach($children as $child){
                   if(\Yii::$app->user->can($child->url)){
                       $item['items'][]=['label'=>$child->label,'url'=>[$child->url]];
                   }

               }
                if(!empty($item['items'])){
                   $menuItems[] = $item;
                }


            }
            $menuItems[] = ['label' => '退出('.\Yii::$app->user->identity->username.')', 'url' => ['user/logout']];
        }
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => $menuItems,
        ]);//输出导航条链接
        NavBar::end();
    }
}